create database MB1;
USE MB1;
CREATE table STUDENT(id int,name varchar(30),age int,place varchar(30),phone bigint,primary key(id));
select * from student;
insert into student(id,name,age,place,phone) values(1,"kevin",22,"chalakudy",9562640213),(2,"smera",20,"mannuthy",9847830656);
insert into student values (3,"jose",50,"pariyaram",6235393065),(4,"shiji",45,"kochi",953478568);
update student set place="thrissur" where id=3;
update student set age=45 where id=3;
create table newstudent like student;
select * from newstudent;
insert into newstudent select * from student;
delete from newstudent where id=1;
select name,place from newstudent;
select * from newstudent where place="kochi";
select name,phone from newstudent where place="kochi";
select * from newstudent where age>25;
select distinct place from newstudent;
select * from newstudent order by place asc;
select name,phone from newstudent order by place desc;
select * from newstudent order by place desc;
